#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2004-2012 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#
# Portions Copyright [2016] [Payara Foundation]

example.message1=JTS0001:Test Message. Parameter 1={0} parameter 2={1}
example.message2=JTS0002:Date Message. Parameter 1={0,date} Parameter 2={1,time}
example.message3=JTS0003:Number Message. Parameter 1={0,number,integer}
jts.create_control_object_error=JTS5001: Cannot create control object reference.
JTS5001.diag.cause.1=Servant is already active.
JTS5001.diag.cause.2=Servant is not active.
JTS5001.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.cannot_locate_servant=JTS5002: Cannot locate [{0}] servant.
JTS5002.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.object_destroy_error=JTS5003: Cannot destroy [{0}] object reference.
JTS5003.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.create_coordinator_object_error=JTS5004: Cannot create coordinator object reference
JTS5004.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.wait_for_resync_complete_interrupted=JTS5005: Wait for resync complete interrupted
JTS5005.diag.cause.1=Recovery or resync process got interrupted.
JTS5005.diag.check.1=See the server log for more details.
jts.unable_to_convert_object_reference_to_string_in_recovery= JTS5006: Unable to convert object reference to string in recovery.
JTS5006.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.cannot_initialise_log=JTS5007: Cannot initialise log.
JTS5007.diag.check.1=See the server log for more details.
JTS5007.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.cannot_open_log_file=JTS5008: Cannot open log file for server=[{0}].
JTS5008.diag.check.1=Transaction log directory is not accessible.
JTS5008.diag.cause.1=Make sure, Transaction log directory (transaction-service.tx-log-dir in server configuration file) is proper andhas the read, write permissions for the user of the application server.
jts.create_CoordinatorResource_object_error=JTS5009: Cannot create CoordinatorResource object reference
JTS5009.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.create_CoordinatorSynchronization_object_error=JTS5010: Cannot create CoordinatorSynchronization object reference
JTS5010.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.no_coordinator_available=JTS5011: No coordinator available.
JTS5011.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.unexpected_error_in_begin=JTS5012: Unexpected error occurred when trying to begin a new transaction.
JTS5012.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.unable_to_create_subordinate_coordinator=JTS5013: Unable to create a subordinate Coordinator.
JTS5013.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.startup_msg=JTS5014: Recoverable JTS instance, serverId=[{0}]
jts.unexpected_error_when_creating_poa=JTS5015: Unexpected error occurred when creating portable object adaptors
JTS5015.diag.cause.1=ORB may not be running.
JTS5015.diag.check.1=Make sure that ORB is running.
JTS5015.diag.check.2=If ORB is running, this is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.unexpected_error_when_creating_current=JTS5016: Unexpected error occurred when creating current object
JTS5016.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.orb_not_running=JTS5017: The ORB daemon, ORBD, is not running.
jts.cannot_register_with_orb=JTS5018: Cannot register [{0}] instance with the ORB.
JTS5018.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.non_persistent_server=JTS5019: This is a non-persistent servers. Transactions will not be recoverable.
jts.invalid_log_path=JTS5020: Invalid log path.  Using [{0}].
JTS5020.diag.cause.1=Configuration problem while giving the log path.
JTS5020.diag.check.1=Check the Transaction log path in server configuration file (transaction-service.tx-log-dir).
jts.invalid_default_log_path =JTS5021: Invalid default log path.  Using current directory.
jts.log_error=JTS5022: Unexpected exception [{0}] from log.
JTS5022.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
JTS5022.diag.check.2=Make sure Transaction log directory (transaction-service.tx-log-dir in server configuration file) is valid, not corrupted,  and has the read, write permissions for the user of the application server. You may also need to restart the application server.
jts.heuristic_exception=JTS5023: Heuristic exception [{0}] cannot be reported to superior in resync.
jts.create_recoverycoordinator_error=JTS5024: Cannot create RecoveryCoordinator object reference.
JTS5024.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.log_file_transient_server=JTS5025: Log file exists for transient server [{0}].
jts.recovery_in_doubt=JTS5026: Exception [{0}] recovering an in-doubt Coordinator.
JTS5026.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.resync_failed=JTS5027: Exception [{0}] on [{1}] operation during resync.
JTS5027.diag.check.1=See the server log for more details.
jts.xaexception_in_recovery=JTS5028: XAException occurred during recovery of XAResource objects; XA Error Code : [{0}]
JTS5028.diag.cause.1=XAResource.recover has thrown an exception during recovery.
JTS5028.diag.check.1=See the exception Stack trace for more details.
jts.exception_during_resync=JTS5029: Exception [{0}] on [{1}] operation during resync.
JTS5029.diag.check.1=See the server log for more details.
jts.restart_write_failed=JTS5030: Unable to write restart record.
JTS5030.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.exception_on_resource_operation=JTS5031: Exception [{0}] on Resource [{1}] operation.
JTS5031.diag.check.1=See the server log for more details.
jts.retry_limit_exceeded=JTS5032: Retry limit of [{0}] [{1}] operations exceeded.
JTS5032.diag.cause.1=Server could not communicate with the resource manager with in the retry limit.
JTS5032.diag.check.1=Make sure that resource manager is up and running or increase the retry limit (transaction-service.retry-timeout-in-seconds in the server configuration file).
jts.exception_in_synchronization_operation=JTS5033: Exception [{0}] on [{1}] synchronization operation.
JTS5033.diag.check.1=See the server log for more details.
jts.already_indetified_communication_manager=JTS5034: Already identified to communications manager.
JTS5034.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.unable_to_indetify_communication_manager=JTS5035: Unable to identify to communications manager.
JTS5035.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.transaction_wrong_state=JTS5036: Transaction in the wrong state for [{0}] operation.
JTS5036.diag.check.1=See the server log for more details.
JTS5036.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.create_terminator_object_error=JTS5037: Cannot create Terminator object reference.
JTS5037.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.transaction_resync_from_orginator_failed=JTS5038: Transaction resynchronization from originator failed,retrying....
jts.time_out_thread_stopped=JTS5039: Timeout thread stopped
jts.create_transactionfactory_object_error=JTS5040: Cannot create TransactionFactory object reference.
JTS5040.diag.cause.1=ORB may not be running.
JTS5040.diag.check.1=See the server log for more details.
JTS5040.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.resource_outside_transaction=JTS5041: The resource manager is doing work outside a global transaction
JTS5041.diag.cause.1=Database driver or Resource Adapter has thrown XAException with the error message "The resource manager is doing work outside a global transaction"
JTS5041.diag.check.1=Check if the application is using the same XA pool outside the transactional context as well as in the transactional context. Some drivers do not allow this scenario. Another scenario to verify is, two separate XA pools pointing to the same backend with the same credentials and the second connection is obtained with in the same transaction, without closing the first connection.
jts.unexpected_error_in_getstatus=JTS5042: Unexpected error occurred while getting the status of the transaction
JTS5042.diag.check.1=See the server log for more details.
JTS5042.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.unexpected_error_in_create_transaction_manager=JTS5043: Unexpected error occurred while creating transaction manager instance
JTS5043.diag.check.1=See the server log for more details.
JTS5043.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.unexpected_error_in_get_or_create_transaction_state=JTS5044: Unexpected error occurred while getting or creating transaction state
jts.unexpected_error_in_beforecompletion=JTS5045: Unexpected error occurred in beforeCompletion
jts.transaction_inactive=JTS5046: Transaction is not active
jts.object_unavailable=JTS5047: Transaction object not available
jts.assert=JTS5048: Assert condition not satisfied
JTS5048.diag.check.1=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.create_xaresource_object_error=JTS5049: Cannot create XAResource object reference.
JTS5049.diag.check.1=See the server log for more details.
JTS5049.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.invalid_timeout=JTS5050: Invalid timeout value. Negative values are illegal.
jts.invalid_state_change=JTS5051: Invalid transaction state change
JTS5051.diag.check.1=See the server log for more details.
JTS5051.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.transaction_id_already_in_use=JTS5052: Transaction id is already in use.
jts.invalid_log_record_data=JTS5053: Invalid log record data in section [{0}].
JTS5053.diag.check.1=See the server log for more details.
JTS5053.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.unexpected_error_occurred_in_after_completion=JTS5054: Unexpected error occurred in after completion
JTS5054.diag.cause.1=One or more SynchronizationImpls beforeCompletion or afterCompletion methods have thrown unexpected exception.
jts.unexpected_error_in_getcorbareference=JTS5055: Unexpected error occurred in getCORBAReference
JTS5055.diag.check.1=See the server log for more details.
JTS5055.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.invalid_wait_point=JTS5056: Invalid wait point
JTS5056.diag.check.1=Make sure to call FailureInducer.setWaitPoint() with a valid WaitPoint.
jts.failpoint=JTS5057: FailPoint : [{0}]
jts.invalid_crash_point=JTS5058: Invalid crash point
JTS5058.diag.check.1=Make sure to call FailureInducer.setWaitPoint() with a valid WaitPoint.
jts.recovery_in_doubt_exception=JTS5059: Exception recovering an in-doubt Coordinator
JTS5059.diag.check.1=See the server log for more details.
JTS5059.diag.check.2=This is an Unexpected Internal Error. Please contact support with the complete error log message.
jts.error_while_setting_txn_timeout=JTS5060: Exception occurred while setting transaction timeout
jts.error_while_enabling_monitoring=JTS5061: Exception occurred while enabling transaction monitoring
jts.error_while_setting_xares_txn_timeout=JTS5062: Exception occurred while setting XAResource timeout
JTS5062.diag.check.1=See the server log for more details. XAResource.setTransactionTimeout() might not be supported for this XAResource.
jts.unexpected_xa_error_in_beforecompletion=JTS5063: Unexpected error occurred in beforeCompletion, XA Error Code : [{0}], Error Message : [{1}]
jts.delist_exception=JTS5064: Unexpected exception occurred while delisting the resource
JTS5064.diag.cause.1=Unexpected exception thrown from XAResource.end.
JTS5064.diag.check.1=See the server log for more details.
jts.exception_in_recovery_file_handling=JTS5065: An IO Exception occurred while handling recovery file
JTS5065.diag.cause.1=Transaction Log directory path is not valid or proper permissions are not there.
JTS5065.diag.check.1=Make sure that transaction log directory is valid and files in that directory have read write permissions.
jts.log_exception_at_recovery=JTS5066: Unexpected error occurred in recovery process. Possible cause is that transaction logs are corrupted. Please clean up the transaction-service.tx-log-dir/tx/* files and restart the server.
JTS5066.diag.cause.1=Possible cause is that transaction logs are corrupted.
JTS5066.diag.check.1=Please clean up the transaction-service.tx-log-dir/tx/* files and restart the server.
jts.unexpected_error_occurred_twopc_commit=JTS5067: Unexpected error occurred in commit
jts.unexpected_error_occurred_twopc_rollback=JTS5068: Unexpected error occurred in rollback
jts.exception_in_db_log_resource=JTS5069: Exception occurred while accessing JDBC resource for transaction log.
jts.unconfigured_db_log_resource=JTS5070: Exception occurred while obtaining JDBC resource [{0}] for transaction log.
jts.exception_in_register_synchronization=JTS5071: Unexpected error occurred in registerSynchronization
jts.before_recovery_excep=JTS5072: Caught exception during beforeRecovery event for {0}
JTS5072.diag.cause.1=Exception occurred while calling beforeRecovery event on the registered listener
JTS5072.diag.check.1=Check exception message for the exact cause of the exception
jts.after_recovery_excep=JTS5073: Caught exception during afterRecovery event for {0}
JTS5073.diag.cause.1=Exception occurred while calling afterRecovery event on the registered listener
JTS5073.diag.check.1=Check exception message for the exact cause of the exception
jts.recovery_error=JTS5074: Error while doing the transaction recovery.
JTS5074.diag.cause.1=Exception occurred while performing delegated recovery
JTS5074.diag.check.1=Check exception message for the exact cause of the exception
jts.error_updating_gms=JTS5075: Error while updating GMS
JTS5075.diag.cause.1=Exception occurred while updating GMS
JTS5075.diag.check.1=Check exception message for the exact cause of the exception
jts.error_wait_time_before_recovery=JTS5076: Invalid wait time for the recovery
JTS5076.diag.cause.1=wait-time-before-recovery-insec property is not set to a valid integer
JTS5076.diag.check.1=Check wait-time-before-recovery-insec property value
jts.error_getting_member_details=JTS5077: Transaction log location data is not available for failed Member details for {0}
JTS5077.diag.cause.1=Could happen if instance fails BEFORE actually getting this info into distributed state cache.
JTS5077.diag.cause.2=Could also be a GMS distributed state cache bug.
JTS5077.diag.check.1=Check if ''asadmin recover-transactions'' can be used instead. Report the problem if it persists.
jts.exception_in_db_log_resource_create=JTS5078: Table for transaction logging was not added.
jts.exception_in_db_log_table_create_error=JTS5079: Failed to create table for transaction logging on this instance. If the table already existed and was expected to be created by this instance, ignore this error.
jts.exception_in_db_log_server_to_instance_mapping=JTS5080: Replacing mapping record in the transaction logging table for instance [{0}] from [{1}] to [{2}]
jts.exception_creating_recovery_file=JTS5081: An IO Exception occurred while creating recovery file [{0}]
JTS5081.diag.cause.1=Transaction Log directory path is not valid or proper permissions are not there.
JTS5081.diag.check.1=Make sure that transaction log directory is valid and files in that directory have read write permissions.
jts.exception_creating_log_directory=JTS5082: Failed to create transaction log directory [{0}]
JTS5082.diag.cause.1=Transaction Log directory path is not valid or proper permissions are not there.
JTS5082.diag.check.1=Make sure that transaction log directory is valid and files in that directory have read write permissions.

## IIOP Section
iiop.readproperty_exception=IOP5015: Unable to read transaction.interoperability config property
